### PR TITLE
Fix typo in HttpApiClient

### PR DESCRIPTION
**Pull request by LordSimal**
apiHost was not working because of this small typo 😉

### CODE REVIEW

**Comment by jeromegamez** [comment]
Huch! Thank you! Could you please add a curly brace instead of removing it? Just so it's the same interpolation everywhere 😅

**Comment by jeromegamez** [comment]
Note to self: add proper tests 😅

**Comment by LordSimal** [comment]
There you go 😄

**Comment by jeromegamez** [comment]
Thank you! 🌺

**Comment by jeromegamez** [comment]
Aaaaand here's the release: [2.0.1](https://github.com/jeromegamez/mite-php/releases/tag/2.0.1)

**Pull request merged**
